version: '3.8'

services:
  github-langs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=local
      - TOKEN=token
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app
